[package]
name = "exfat"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive", "min_const_generics"] }
checked_num = "0.1.3"
derive_builder = "0.20.2"
thiserror = "2.0.11"
