name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:
    strategy: 
      matrix:
        os: [ubuntu, macos, windows]
        toolchain: [stable, nightly]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        components: "rustfmt, clippy"
    
    - name: Build
      run: cargo build
      
    - name: Lint
      run: cargo clippy
      
    - name: Check formatting
      run: cargo fmt --check
      
    - name: Run tests
      run: cargo test
